package common

const RESULT_STATUS_SUCCESS = "SUCCESS"
const RESULT_STATUS_FAIL = "FAIL"

const EMPTY_STR = "-"

const OK = "OK"
const ALL_NAMESPACE = "all"

// VAULT
const FAILED_TO_READ_CLUSTER_DATA = "FAILED_TO_READ_CLUSTER_DATA"
const FAILED_TO_PARSE_VALUES = "FAILED_TO_PARSE_VALUES"

// REPOSITORY
const REPO_NAME_URL_REQUIRED = "REPO_NAME_URL_REQUIRED"
const REPO_NAME_CONTAINS_SC = "REPO_NAME_CONTAINS_SC"
const REPO_NAME_ALREADY_EXISTS = "REPO_NAME_ALREADY_EXISTS"
const REPO_USERNAME_PASSWD_REQUIRED = "REPO_USERNAME_PASSWD_REQUIRED"
const REPO_SAME_CONF_ALREADY_EXISTS = "REPO_SAME_CONF_ALREADY_EXISTS"
const REPO_CANNOT_BE_REACHED = "REPO_CANNOT_BE_REACHED"
const REPO_NO_CONFIGURED = "REPO_NO_CONFIGURED"
const REPO_NO_NAMED_FOUND = "REPO_NO_NAMED_FOUND"
const REPO_UNABLE_UPDATE = "REPO_UNABLE_UPDATE"
const REPO_FAILED_LOADING_FILE = "REPO_FAILED_LOADING_FILE"
const REPO_CORRUPT_MISSING = "REPO_CORRUPT_MISSING"
const REPO_CA_INVALID = "REPO_CA_INVALID"
const REPO_CA_FAILED_SAVE = "REPO_CA_FAILED_SAVE"
const INSTALLATION_FAILED = "INSTALLATION_FAILED"

const CHART_INFO_INVALID = "CHART_INFO_INVALID"
const CHART_VERSION_INVALID = "CHART_VERSION_INVALID"
const REVERSION_NUMBER_INVALID = "REVERSION_NUMBER_INVALID"
const RELEASE_NOT_FOUND = "RELEASE_NOT_FOUND"
const RELEASE_ALREADY_EXISTS = "RELEASE_ALREADY_EXISTS"
