basePath: /
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: K-PaaS Container Platform Helm Rest API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Container Platform Helm Rest API
  version: "1.0"
paths:
  /api/repositories:
    get:
      consumes:
      - application/json
      description: List Repository
      produces:
      - application/json
      responses: {}
      summary: List Repository
    post:
      consumes:
      - application/json
      description: Add Repository
      produces:
      - application/json
      responses: {}
      summary: Add Repository
swagger: "2.0"
