basePath: /
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: K-PaaS Container Platform Helm Rest API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Container Platform Helm Rest API
  version: "1.0"
paths:
  /api/clusters/:clusterId/namespaces/:namespace/releases:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: List Releases
      tags:
      - Releases
  /api/clusters/:clusterId/namespaces/:namespace/releases/:release:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Uninstall Release
      tags:
      - Releases
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get Releases Info
      tags:
      - Releases
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Install Release
      tags:
      - Releases
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Upgrade Release
      tags:
      - Releases
  /api/clusters/:clusterId/namespaces/:namespace/releases/:release/histories:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get Release Histories
      tags:
      - Releases
  /api/clusters/:clusterId/namespaces/:namespace/releases/:release/resources:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get Release Resources
      tags:
      - Releases
  /api/clusters/:clusterId/namespaces/:namespace/releases/:release/versions/:reversion:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Rollback Release
      tags:
      - Releases
  /api/repositories:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: List Repository
      tags:
      - Repository
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Add Repository
      tags:
      - Repository
swagger: "2.0"
